apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaker
spec:
  selector:
    matchLabels:
      app: matchmaker
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: matchmaker
        tier: backend
        track: stable
    spec:
      containers:
        - name: matchmaker
          image: "gcr.io/silver-osprey-217701/matching:latest"
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "gunicorn -b :5000 main:app --timeout 60"]
          ports:
            - name: http
              containerPort: 5000