# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PilotCityApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PilotCityApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SVProgressHUD'
  target 'PilotCityAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PilotCityAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
