runtime: python27
api_version: 1
service: default
threadsafe: true

handlers:
# root
- url: /$
  static_files: public/index.html
  upload: public/index.html

- url: /aboutyou
  static_files: public/who_are_you.html
  upload: public/who_are_you.html

- url: /(.+)
  static_files: public/\1
  upload: public/(.*)
