runtime: python27
api_version: 1
service: default
threadsafe: true

handlers:
# root
- url: /
  static_files: frontPage/front_page.html
  upload: frontPage/front_page.html

- url: /(.+)
  static_files: \1
  upload: (.+)
